require("pluginconfig.lsp")
require("pluginconfig.line")
require("pluginconfig.pair")
require("pluginconfig.syntax")
require("pluginconfig.term")
require("pluginconfig.tele")
require("pluginconfig.snip")
require("pluginconfig.colors")
